name = feedhook
title = FeedHook

version = 1.0.0
version_min = 5.0.0

description = This mod adds a new /suggestion command that sends this suggestion directly to discord with a webhook
Author = Smnoe01

depends = 
optional_depends =